#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run shell:utils:env_example
npm run shell:utils:clasp_reset
git add .env.example

# this fixes exccessive output when running just "lint-staged"
exec >/dev/console 2>&1
npm run lint-staged:run

npm run test
